// src/app/master-view/backlog/backlog.tsx
import { IgrAvatar, IgrAvatarModule, IgrButton, IgrButtonModule, IgrIconButton, IgrIconButtonModule, IgrInput, IgrInputModule, IgrList, IgrListHeader, IgrListHeaderModule, IgrListItem, IgrListModule, IgrRipple, IgrRippleModule, IgrTab, IgrTabPanel, IgrTabs, IgrTabsModule } from 'igniteui-react';
import { IgrColumn, IgrGrid, IgrGridModule } from 'igniteui-react-grids';
import { useState } from 'react';
import { useGetCustomers, useGetEmployees, useGetOrders, useGetSuppliers } from '../../hooks/northwind-hooks';
import 'igniteui-react-grids/grids';
import styles from './backlog.module.css';
import createClassTransformer from '../../style-utils';

IgrAvatarModule.register();
IgrButtonModule.register();
IgrGridModule.register();
IgrIconButtonModule.register();
IgrInputModule.register();
IgrListHeaderModule.register();
IgrListModule.register();
IgrRippleModule.register();
IgrTabsModule.register();

export default function Backlog() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const [groupVisible, setGroupVisible] = useState<boolean | undefined>(false);
  const { northwindOrders } = useGetOrders();
  const { northwindCustomers } = useGetCustomers();
  const { northwindEmployees } = useGetEmployees();
  const { northwindSuppliers } = useGetSuppliers();

  return (
    <>
      <div className={classes("row-layout backlog-container")}>
        <div className={classes("column-layout left-nav")}>
          <h6 className={classes("h6")}>
            <span>Backlog</span>
          </h6>
          <IgrList className={classes("list")}>
            <IgrListHeader key={uuid()}>
              <div key={uuid()}>INDIGO.DESIGN</div>
            </IgrListHeader>
            <IgrListItem key={uuid()}>
              <div slot="start" key={uuid()}>
                <IgrAvatar className={classes("avatar avatar_1")} key={uuid()}>
                  <span className={classes("material-icons icon")} key={uuid()}>
                    <span key={uuid()}>dashboard</span>
                  </span>
                </IgrAvatar>
              </div>
              <div slot="title" key={uuid()}>Growth Hacking</div>
            </IgrListItem>
            <IgrListItem key={uuid()}>
              <div slot="start" key={uuid()}>
                <IgrAvatar className={classes("avatar avatar_2")} key={uuid()}>
                  <span className={classes("material-icons icon")} key={uuid()}>
                    <span key={uuid()}>dashboard</span>
                  </span>
                </IgrAvatar>
              </div>
              <div slot="title" key={uuid()}>Public Preview</div>
            </IgrListItem>
            <IgrListItem key={uuid()}>
              <div slot="start" key={uuid()}>
                <IgrAvatar className={classes("avatar avatar_3")} key={uuid()}>
                  <span className={classes("material-icons icon")} key={uuid()}>
                    <span key={uuid()}>dashboard</span>
                  </span>
                </IgrAvatar>
              </div>
              <div slot="title" key={uuid()}>UX Feedback</div>
            </IgrListItem>
          </IgrList>
          <IgrButton variant="flat" type="button" className={classes("button")}>
            <span className={classes("material-icons")} key={uuid()}>
              <span key={uuid()}>add</span>
            </span>
            <span key={uuid()}>ADD NEW PROJECT</span>
            <IgrRipple key={uuid()}></IgrRipple>
          </IgrButton>
        </div>
        <div className={classes("row-layout right-container")}>
          <div className={classes("column-layout content")}>
            <div className={classes("row-layout content-toolbar")}>
              <h5 className={classes("h5")}>
                <span>Growth Hacking</span>
              </h5>
              <div className={classes("row-layout group")}>
                <IgrButton variant="flat" type="button" className={classes("button_1")}>
                  <span className={classes("material-icons")} key={uuid()}>
                    <span key={uuid()}>settings</span>
                  </span>
                  <span key={uuid()}>Settings</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
                <IgrIconButton variant="flat" clicked={() => setGroupVisible(!groupVisible)} className={classes("icon-button")}>
                  <span className={classes("material-icons icon_1")} key={uuid()}>
                    <span key={uuid()}>filter_list</span>
                  </span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrIconButton>
              </div>
            </div>
            {groupVisible && (
              <div className={classes("row-layout filters")}>
                <div className={classes("row-layout group_1")}>
                  <IgrInput label="Filter by keyword" outlined="false" className={classes("input")}></IgrInput>
                </div>
                <div className={classes("row-layout group_2")}>
                  <IgrButton variant="flat" type="button" className={classes("button_1")}>
                    <span key={uuid()}>Assigned to</span>
                    <span className={classes("material-icons")} key={uuid()}>
                      <span key={uuid()}>keyboard_arrow_down</span>
                    </span>
                    <IgrRipple key={uuid()}></IgrRipple>
                  </IgrButton>
                  <IgrButton variant="flat" type="button" className={classes("button_1")}>
                    <span key={uuid()}>Iteration</span>
                    <span className={classes("material-icons")} key={uuid()}>
                      <span key={uuid()}>keyboard_arrow_down</span>
                    </span>
                    <IgrRipple key={uuid()}></IgrRipple>
                  </IgrButton>
                  <IgrButton variant="flat" type="button" className={classes("button_1")}>
                    <span key={uuid()}>Area</span>
                    <span className={classes("material-icons")} key={uuid()}>
                      <span key={uuid()}>keyboard_arrow_down</span>
                    </span>
                    <IgrRipple key={uuid()}></IgrRipple>
                  </IgrButton>
                  <IgrIconButton variant="flat" clicked={() => setGroupVisible(!groupVisible)} className={classes("icon-button_1")}>
                    <span className={classes("material-icons")} key={uuid()}>
                      <span key={uuid()}>close</span>
                    </span>
                    <IgrRipple key={uuid()}></IgrRipple>
                  </IgrIconButton>
                </div>
              </div>
            )}
            <IgrTabs className={classes("tabs")}>
              <IgrTab selected="true" key={uuid()}>
                <span key={uuid()}>Q1</span>
              </IgrTab>
              <IgrTabPanel className={classes("column-layout tab-item-content")} key={uuid()}>
                <IgrGrid data={northwindOrders} primaryKey="employeeID" allowFiltering="true" filterMode="excelStyleFilter" className={classes("ig-typography ig-scrollbar grid")}>
                  <IgrColumn field="orderID" dataType="number" header="orderID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="customerID" dataType="string" header="customerID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="employeeID" dataType="number" header="employeeID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="orderDate" dataType="date" header="orderDate" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="requiredDate" dataType="date" header="requiredDate" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shippedDate" dataType="date" header="shippedDate" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipVia" dataType="number" header="shipVia" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="freight" dataType="number" header="freight" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipName" dataType="string" header="shipName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipAddress.street" dataType="string" header="street" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipAddress.city" dataType="string" header="city" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipAddress.region" dataType="string" header="region" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipAddress.postalCode" dataType="string" header="postalCode" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="shipAddress.country" dataType="string" header="country" sortable="true" selectable="false"></IgrColumn>
                </IgrGrid>
              </IgrTabPanel>
              <IgrTab disabled="true" key={uuid()}>
                <span key={uuid()}>Q2</span>
              </IgrTab>
              <IgrTabPanel className={classes("row-layout tab-item-content")} key={uuid()}>
                <IgrGrid data={northwindCustomers} primaryKey="customerID" allowFiltering="true" filterMode="excelStyleFilter" className={classes("ig-typography ig-scrollbar grid_1")}>
                  <IgrColumn field="customerID" dataType="string" header="customerID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="companyName" dataType="string" header="companyName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="contactName" dataType="string" header="contactName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="contactTitle" dataType="string" header="contactTitle" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.street" dataType="string" header="address street" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.city" dataType="string" header="address city" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.region" dataType="string" header="address region" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.postalCode" dataType="string" header="address postalCode" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.country" dataType="string" header="address country" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.phone" dataType="string" header="address phone" sortable="true" selectable="false"></IgrColumn>
                </IgrGrid>
              </IgrTabPanel>
              <IgrTab disabled="true" key={uuid()}>
                <span key={uuid()}>Q3</span>
              </IgrTab>
              <IgrTabPanel className={classes("row-layout tab-item-content")} key={uuid()}>
                <IgrGrid data={northwindEmployees} primaryKey="employeeID" allowFiltering="true" filterMode="excelStyleFilter" className={classes("ig-typography ig-scrollbar grid_1")}>
                  <IgrColumn field="employeeID" dataType="number" header="employeeID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="lastName" dataType="string" header="lastName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="firstName" dataType="string" header="firstName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="title" dataType="string" header="title" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="titleOfCourtesy" dataType="string" header="titleOfCourtesy" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="birthDate" dataType="date" header="birthDate" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="hireDate" dataType="date" header="hireDate" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.street" dataType="string" header="address street" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.city" dataType="string" header="address city" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.region" dataType="string" header="address region" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.postalCode" dataType="string" header="address postalCode" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.country" dataType="string" header="address country" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.phone" dataType="string" header="address phone" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="managerID" dataType="number" header="managerID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="notes" dataType="string" header="notes" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="avatarUrl" dataType="string" header="avatarUrl" sortable="true" selectable="false"></IgrColumn>
                </IgrGrid>
              </IgrTabPanel>
              <IgrTab disabled="true" key={uuid()}>
                <span key={uuid()}>Q4</span>
              </IgrTab>
              <IgrTabPanel className={classes("row-layout tab-item-content")} key={uuid()}>
                <IgrGrid data={northwindSuppliers} primaryKey="supplierID" allowFiltering="true" filterMode="excelStyleFilter" className={classes("ig-typography ig-scrollbar grid_1")}>
                  <IgrColumn field="supplierID" dataType="number" header="supplierID" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="companyName" dataType="string" header="companyName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="contactName" dataType="string" header="contactName" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="contactTitle" dataType="string" header="contactTitle" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.street" dataType="string" header="address street" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.city" dataType="string" header="address city" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.region" dataType="string" header="address region" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.postalCode" dataType="string" header="address postalCode" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.country" dataType="string" header="address country" sortable="true" selectable="false"></IgrColumn>
                  <IgrColumn field="address.phone" dataType="string" header="address phone" sortable="true" selectable="false"></IgrColumn>
                </IgrGrid>
              </IgrTabPanel>
            </IgrTabs>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/master-view/backlog/backlog.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { IGX_GRID_DIRECTIVES, IGX_INPUT_GROUP_DIRECTIVES, IGX_LIST_DIRECTIVES, IGX_TABS_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxIconButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from 'igniteui-angular';
import { Subject, takeUntil } from 'rxjs';
import { SuppliersType } from '../../models/northwind/suppliers-type';
import { OrdersType } from '../../models/northwind/orders-type';
import { EmployeesType } from '../../models/northwind/employees-type';
import { CustomersType } from '../../models/northwind/customers-type';
import { NorthwindService } from '../../services/northwind.service';

@Component({
  selector: 'app-backlog',
  imports: [IGX_GRID_DIRECTIVES, IGX_INPUT_GROUP_DIRECTIVES, IGX_LIST_DIRECTIVES, IGX_TABS_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxIconButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './backlog.component.html',
  styleUrls: ['./backlog.component.scss']
})
export class BacklogComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  public groupVisible: boolean = false;
  public northwindOrders: OrdersType[] = [];
  public northwindCustomers: CustomersType[] = [];
  public northwindEmployees: EmployeesType[] = [];
  public northwindSuppliers: SuppliersType[] = [];

  constructor(private northwindService: NorthwindService) { }

  ngOnInit() {
    this.northwindService.getOrders().pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindOrders = data,
      error: (_err: any) => this.northwindOrders = []
    });
    this.northwindService.getCustomers().pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindCustomers = data,
      error: (_err: any) => this.northwindCustomers = []
    });
    this.northwindService.getEmployees().pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindEmployees = data,
      error: (_err: any) => this.northwindEmployees = []
    });
    this.northwindService.getSuppliers().pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindSuppliers = data,
      error: (_err: any) => this.northwindSuppliers = []
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="column-layout left-nav">
  <h6 class="h6">
    Backlog
  </h6>
  <igx-list class="list">
    <igx-list-item [isHeader]="true">INDIGO.DESIGN</igx-list-item>
    <igx-list-item>
      <span igxListThumbnail>
        <igx-avatar class="avatar">
          <igx-icon class="icon">
            dashboard
          </igx-icon>
        </igx-avatar>
      </span>
      <span igxListLineTitle>Growth Hacking</span>
    </igx-list-item>
    <igx-list-item>
      <span igxListThumbnail>
        <igx-avatar class="avatar_1">
          <igx-icon class="icon">
            dashboard
          </igx-icon>
        </igx-avatar>
      </span>
      <span igxListLineTitle>Public Preview</span>
    </igx-list-item>
    <igx-list-item>
      <span igxListThumbnail>
        <igx-avatar class="avatar_2">
          <igx-icon class="icon">
            dashboard
          </igx-icon>
        </igx-avatar>
      </span>
      <span igxListLineTitle>UX Feedback</span>
    </igx-list-item>
  </igx-list>
  <button igxButton="flat" type="button" igxRipple class="button">
    <igx-icon>
      add
    </igx-icon>
    <span>ADD NEW PROJECT</span>
  </button>
</div>
<div class="row-layout right-container">
  <div class="column-layout content">
    <div class="row-layout content-toolbar">
      <h5 class="h5">
        Growth Hacking
      </h5>
      <div class="row-layout group">
        <button igxButton="flat" type="button" igxRipple class="button_1">
          <igx-icon>
            settings
          </igx-icon>
          <span>Settings</span>
        </button>
        <button igxRipple igxIconButton="flat" (click)="groupVisible = !groupVisible" class="icon-button">
          <igx-icon class="icon_1">
            filter_list
          </igx-icon>
        </button>
      </div>
    </div>
    @if (groupVisible) {
      <div class="row-layout filters">
        <div class="row-layout group_1">
          <igx-input-group type="box" class="input">
            <input type="text" igxInput />
            <label igxLabel>Filter by keyword</label>
          </igx-input-group>
        </div>
        <div class="row-layout group_2">
          <button igxButton="flat" type="button" igxRipple class="button_1">
            <span>Assigned to</span>
            <igx-icon>
              keyboard_arrow_down
            </igx-icon>
          </button>
          <button igxButton="flat" type="button" igxRipple class="button_1">
            <span>Iteration</span>
            <igx-icon>
              keyboard_arrow_down
            </igx-icon>
          </button>
          <button igxButton="flat" type="button" igxRipple class="button_1">
            <span>Area</span>
            <igx-icon>
              keyboard_arrow_down
            </igx-icon>
          </button>
          <button igxRipple igxIconButton="flat" (click)="groupVisible = !groupVisible" class="icon-button_1">
            <igx-icon>
              close
            </igx-icon>
          </button>
        </div>
      </div>
    }
    <igx-tabs [disableAnimation]="true" class="tabs">
      <igx-tab-item [selected]="true" class="tab-item">
        <igx-tab-header>
          <span igxTabHeaderLabel>Q1</span>
        </igx-tab-header>
        <igx-tab-content class="column-layout tab-item-content">
          <igx-grid [data]="northwindOrders" primaryKey="employeeID" [allowFiltering]="true" filterMode="excelStyleFilter" class="grid">
            <igx-column field="orderID" dataType="number" header="orderID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="customerID" dataType="string" header="customerID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="employeeID" dataType="number" header="employeeID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="orderDate" dataType="date" header="orderDate" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="requiredDate" dataType="date" header="requiredDate" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shippedDate" dataType="date" header="shippedDate" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipVia" dataType="number" header="shipVia" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="freight" dataType="number" header="freight" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipName" dataType="string" header="shipName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipAddress.street" dataType="string" header="street" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipAddress.city" dataType="string" header="city" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipAddress.region" dataType="string" header="region" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipAddress.postalCode" dataType="string" header="postalCode" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="shipAddress.country" dataType="string" header="country" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
          </igx-grid>
        </igx-tab-content>
      </igx-tab-item>
      <igx-tab-item [disabled]="true" class="tab-item">
        <igx-tab-header>
          <span igxTabHeaderLabel>Q2</span>
        </igx-tab-header>
        <igx-tab-content class="row-layout tab-item-content">
          <igx-grid [data]="northwindCustomers" primaryKey="customerID" [allowFiltering]="true" filterMode="excelStyleFilter" class="grid_1">
            <igx-column field="customerID" dataType="string" header="customerID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="companyName" dataType="string" header="companyName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="contactName" dataType="string" header="contactName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="contactTitle" dataType="string" header="contactTitle" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.street" dataType="string" header="address street" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.city" dataType="string" header="address city" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.region" dataType="string" header="address region" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.postalCode" dataType="string" header="address postalCode" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.country" dataType="string" header="address country" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.phone" dataType="string" header="address phone" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
          </igx-grid>
        </igx-tab-content>
      </igx-tab-item>
      <igx-tab-item [disabled]="true" class="tab-item">
        <igx-tab-header>
          <span igxTabHeaderLabel>Q3</span>
        </igx-tab-header>
        <igx-tab-content class="row-layout tab-item-content">
          <igx-grid [data]="northwindEmployees" primaryKey="employeeID" [allowFiltering]="true" filterMode="excelStyleFilter" class="grid_1">
            <igx-column field="lastName" dataType="string" header="lastName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="employeeID" dataType="number" header="employeeID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="firstName" dataType="string" header="firstName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="title" dataType="string" header="title" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="titleOfCourtesy" dataType="string" header="titleOfCourtesy" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="birthDate" dataType="date" header="birthDate" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="hireDate" dataType="date" header="hireDate" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.street" dataType="string" header="address street" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.city" dataType="string" header="address city" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.region" dataType="string" header="address region" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.postalCode" dataType="string" header="address postalCode" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.country" dataType="string" header="address country" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.phone" dataType="string" header="address phone" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="managerID" dataType="number" header="managerID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="notes" dataType="string" header="notes" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="avatarUrl" dataType="string" header="avatarUrl" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
          </igx-grid>
        </igx-tab-content>
      </igx-tab-item>
      <igx-tab-item [disabled]="true" class="tab-item">
        <igx-tab-header>
          <span igxTabHeaderLabel>Q4</span>
        </igx-tab-header>
        <igx-tab-content class="row-layout tab-item-content">
          <igx-grid [data]="northwindSuppliers" primaryKey="supplierID" [allowFiltering]="true" filterMode="excelStyleFilter" class="grid_1">
            <igx-column field="supplierID" dataType="number" header="supplierID" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="companyName" dataType="string" header="companyName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="contactName" dataType="string" header="contactName" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="contactTitle" dataType="string" header="contactTitle" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.street" dataType="string" header="address street" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.city" dataType="string" header="address city" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.region" dataType="string" header="address region" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.postalCode" dataType="string" header="address postalCode" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.country" dataType="string" header="address country" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
            <igx-column field="address.phone" dataType="string" header="address phone" [filterable]="true" [sortable]="true" [selectable]="false"></igx-column>
          </igx-grid>
        </igx-tab-content>
      </igx-tab-item>
    </igx-tabs>
  </div>
</div>
