// src/app/login/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, IgxCheckboxComponent, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from 'igniteui-angular';

@Component({
  selector: 'app-sign-in',
  imports: [RouterLink, IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, IgxCheckboxComponent, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss']
})
export class SignInComponent {
}

<div class="row-layout left">
  <div class="column-layout group">
    <div class="row-layout group_1">
      <img src="/assets/slingshot-icon.svg" class="image" />
      <p class="ig-typography__subtitle-2 text">
        TEAM COLLABORATION
      </p>
    </div>
    <h5 class="h5">
      Sign in
    </h5>
    <div class="row-layout group_2">
      <button igxButton="contained" type="button" igxRipple class="button">
        <igx-icon>
          donut_small
        </igx-icon>
        <span>Google</span>
      </button>
      <button igxButton="contained" type="button" igxRipple class="button">
        <igx-icon>
          dashboard
        </igx-icon>
        <span>Microsoft</span>
      </button>
      <button igxButton="contained" type="button" igxRipple class="button">
        <igx-icon>
          copyright
        </igx-icon>
        <span>Apple</span>
      </button>
    </div>
    <igx-input-group type="border" class="input">
      <input type="text" igxInput />
      <label igxLabel>Email / username</label>
    </igx-input-group>
    <igx-input-group type="border" class="input">
      <input type="password" igxInput />
      <label igxLabel>Password</label>
    </igx-input-group>
    <igx-checkbox labelPosition="after" class="checkbox">
      Keep me signed in
    </igx-checkbox>
    <button igxButton="contained" type="button" igxRipple routerLink="/master-view/my-tasks" class="button_1">
      Sign in
    </button>
    <a target="_blank" class="ig-typography__body-2 hyperlink">
      Forgot your account?
    </a>
    <button igxButton="outlined" type="button" igxRipple routerLink="/login/create-account" class="button_1">
      Create New Account
    </button>
  </div>
</div>

// src/app/login/sign-in/sign-in.tsx
import { IgrButton, IgrButtonModule, IgrCheckbox, IgrCheckboxModule, IgrInput, IgrInputModule, IgrRipple, IgrRippleModule } from 'igniteui-react';
import { useNavigate } from 'react-router-dom';
import styles from './sign-in.module.css';
import createClassTransformer from '../../style-utils';

IgrButtonModule.register();
IgrCheckboxModule.register();
IgrInputModule.register();
IgrRippleModule.register();

export default function SignIn() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const navigate = useNavigate();

  return (
    <>
      <div className={classes("row-layout sign-in-container")}>
        <div className={classes("row-layout left")}>
          <div className={classes("column-layout group")}>
            <div className={classes("row-layout group_1")}>
              <img src="/src/assets/slingshot-icon.svg" className={classes("image")} />
              <p className={classes("typography__subtitle-2 text")}>
                <span>TEAM COLLABORATION</span>
              </p>
            </div>
            <h5 className={classes("h5")}>
              <span>Sign in</span>
            </h5>
            <div className={classes("row-layout group_2")}>
              <IgrButton type="button" className={classes("button")}>
                <span className={classes("material-icons")} key={uuid()}>
                  <span key={uuid()}>donut_small</span>
                </span>
                <span key={uuid()}>Google</span>
                <IgrRipple key={uuid()}></IgrRipple>
              </IgrButton>
              <IgrButton type="button" className={classes("button")}>
                <span className={classes("material-icons")} key={uuid()}>
                  <span key={uuid()}>dashboard</span>
                </span>
                <span key={uuid()}>Microsoft</span>
                <IgrRipple key={uuid()}></IgrRipple>
              </IgrButton>
              <IgrButton type="button" className={classes("button")}>
                <span className={classes("material-icons")} key={uuid()}>
                  <span key={uuid()}>copyright</span>
                </span>
                <span key={uuid()}>Apple</span>
                <IgrRipple key={uuid()}></IgrRipple>
              </IgrButton>
            </div>
            <IgrInput label="Email / username" outlined="true" className={classes("input")}></IgrInput>
            <IgrInput type="password" label="Password" outlined="true" className={classes("input")}></IgrInput>
            <IgrCheckbox labelPosition="after" className={classes("checkbox")}>
              <span key={uuid()}>Keep me signed in</span>
            </IgrCheckbox>
            <IgrButton type="button" clicked={() => navigate(`/master-view/my-tasks`)} className={classes("button_1")}>
              <span key={uuid()}>Sign in</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
            <a href="" className={classes("typography__body-2 hyperlink")}>
              <span>Forgot your account?</span>
            </a>
            <IgrButton variant="outlined" type="button" clicked={() => navigate(`/login/create-account`)} className={classes("button_1")}>
              <span key={uuid()}>Create New Account</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
          </div>
        </div>
      </div>
    </>
  );
}
