// src/app/login/create-account/create-account.tsx
import { IgrButton, IgrButtonModule, IgrInput, IgrInputModule, IgrRipple, IgrRippleModule } from 'igniteui-react';
import { useNavigate } from 'react-router-dom';
import styles from './create-account.module.css';
import createClassTransformer from '../../style-utils';

IgrButtonModule.register();
IgrInputModule.register();
IgrRippleModule.register();

export default function CreateAccount() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const navigate = useNavigate();

  return (
    <>
      <div className={classes("row-layout create-account-container")}>
        <div className={classes("row-layout left")}>
          <div className={classes("column-layout group")}>
            <div className={classes("row-layout group_1")}>
              <img src="/src/assets/slingshot-icon.svg" className={classes("image")} />
              <p className={classes("typography__subtitle-2 text")}>
                <span>TEAM COLLABORATION</span>
              </p>
            </div>
            <h5 className={classes("h5")}>
              <span>Create your free account</span>
            </h5>
            <IgrInput label="Email / username" outlined="true" className={classes("input")}></IgrInput>
            <IgrInput type="password" label="Password" outlined="true" className={classes("input")}></IgrInput>
            <div className={classes("row-layout group_2")}>
              <IgrInput label="First Name" outlined="true" className={classes("input_1")}></IgrInput>
              <IgrInput label="Last Name" outlined="true" className={classes("input_1")}></IgrInput>
            </div>
            <p className={classes("typography__body-2 text_1")}>
              <span>By providing your information and submitting this form, you are agreeing to Infragistic's Terms of Use and Privacy Policy.</span>
            </p>
            <IgrButton type="button" clicked={() => navigate(`/master-view/my-tasks`)} className={classes("button")}>
              <span key={uuid()}>CREATE NEW ACCOUNT</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
            <div className={classes("row-layout group_3")}>
              <p className={classes("typography__body-2 text_2")}>
                <span>Already have an account?</span>
              </p>
              <a href="" onClick={() => navigate(`/login/sign-in`)} className={classes("typography__body-2 hyperlink")}>
                <span>Sign in</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/login/create-account/create-account.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from 'igniteui-angular';

@Component({
  selector: 'app-create-account',
  imports: [RouterLink, IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './create-account.component.html',
  styleUrls: ['./create-account.component.scss']
})
export class CreateAccountComponent {
}

<div class="row-layout left">
  <div class="column-layout group">
    <div class="row-layout group_1">
      <img src="/assets/slingshot-icon.svg" class="image" />
      <p class="ig-typography__subtitle-2 text">
        TEAM COLLABORATION
      </p>
    </div>
    <h5 class="h5">
      Create your free account
    </h5>
    <igx-input-group type="border" class="input">
      <input type="text" igxInput />
      <label igxLabel>Email / username</label>
    </igx-input-group>
    <igx-input-group type="border" class="input">
      <input type="password" igxInput />
      <label igxLabel>Password</label>
    </igx-input-group>
    <div class="row-layout group_2">
      <igx-input-group type="border" class="input_1">
        <input type="text" igxInput />
        <label igxLabel>First Name</label>
      </igx-input-group>
      <igx-input-group type="border" class="input_1">
        <input type="text" igxInput />
        <label igxLabel>Last Name</label>
      </igx-input-group>
    </div>
    <p class="ig-typography__body-2 text_1">
      By providing your information and submitting this form, you are agreeing to Infragistic's Terms of Use and Privacy Policy.
    </p>
    <button igxButton="contained" type="button" igxRipple routerLink="/master-view/my-tasks" class="button">
      CREATE NEW ACCOUNT
    </button>
    <div class="row-layout group_3">
      <p class="ig-typography__body-2 text_2">
        Already have an account?
      </p>
      <a target="_self" routerLink="/login/sign-in" class="ig-typography__body-2 hyperlink">
        Sign in
      </a>
    </div>
  </div>
</div>
